### ISSUE TITLE
Buy region signs secure

### ISSUE THREAD

**Issue by Blueeyestar** [GentleGravel/BuyRegion#5]
I rent with RedProtec zones thanks to Buyregion. the problem is the user always remove the signs then. Which shouldn't be. I must then always rebuild them because they can no longer extend after the expiration period. Would be great if they are backed up

**Comment by Blueeyestar** [comment]
Did you ever see if you could secure the signs? The users always knock them off :(

**Comment by dsevillamartin** [comment]
I apologize, I really haven't worked on anything related to this plugin in a while. I may try to fix some things, but I'm going to have even less time than I previously did.

I can't promise anything, but I'll try to.

**Comment by dsevillamartin** [comment]
Should be fixed with v2.2.3. Now, only OP, players with `buyregion.admin` permission, and region owners with `buyregion.create` permission. If the player is a member of the region, they won't be able to delete the sign (if they aren't OP or have the admin permission).

Players can still break the blocks to which the sign is attached to though.

Do remember that players can renew regions with `/buyregion renew` and `/buyregion autorenew`. 🙂
